### ISSUE TITLE
Every algorithm used as part of this hash has had CUDA implementations for years.

### ISSUE THREAD

**Issue by kayabaNerve** [deroproject/astrobwt#1]
CUDA SHA3 implementation (there's plenty of others as well): https://github.com/skapix/sha3
7-year old CUDA SALSA20 implementation: https://github.com/moinakg/salsa20_core_cuda
3-year old CUDA BWT implementation: https://github.com/aditya12agd5/cuda_bzip2

**Comment by CaptainDero** [comment]
Let me know if I am undestanding correctly what you are trying to speak.
AstroBWT is ASIC/FPGA/GPU resistant algo. It never implies that it can be never implemented on ASIC/FPGA/GPU. 
Resistant here means that ASIC/FPGA/GPU will not have large/unfair advantage over CPU implementations.
BWT has been resistant to optimizations since ages even before Blockchain-Crypto.
Also AstroBWT code is in Golang and there are convertors which can port/convert Golang code to FPGA with very less efforts/modifications.

**Comment by kayabaNerve** [comment]
Of course. That said, the BWT algorithm described in the research paper, implemented in the above BZip2 lib, offers a 30% speed up. SHA3 is many times faster on a GPU. SALSA20 also is many times faster, yet only on large input sizes (MBs, which isn't the case here).

I'm not denying how resistance is a spectrum. I'm commenting that creating an algorithm where every GPU impl is equivalent in speed is equal, not resistant, and when it's faster on the GPU by greater than 10%, it's no longer resistant. Even if they were 20% slower, it'd still be a bad foot to start on.

If you don't care about this opinion or commentary, feel free to close the issue. If you're sure this isn't an issue, create a bounty.

**Comment by CaptainDero** [comment]
We would be very glad to discuss about AstroBWT implementation with anyone who can design a system which is performing better than CPU cosidering encometrics. 
Is 10-100% improvement can be called fair on investment of 200-500% ? 
If you have any such proposal please feel free to discuss here.

**Comment by kayabaNerve** [comment]
I feel I've been discussing a 10-30% improvement on GPUs which cost the same amount. If you would like to say this isn't an issue, and keep saying your algorithm is GPU resistant, not just GPU equivalent at best, feel free to close this.

In order to be sure, someone needs to create a GPU implementation. It's that simple.

**Comment by danktron** [comment]
Seems it is quite important for you to argue semantics. That said, please build the GPU implementation and you can test your theory. Feel free to close the issue if not.

**Comment by kayabaNerve** [comment]
I honestly don't have the time. I just wanted to provide the info and make sure it was known. If you want to dismiss these concerns, or say they don't matter because it's a 10% improvement for a 500% investment (which is very far from what I was describing), you can close this.

**Comment by danktron** [comment]
Thanks for linking the paper. If you are not going to build a test case to backup your claim, I would suggest that you close the issue.
