### ISSUE TITLE
Read more about FPGA BWT implementation (link broken)

### ISSUE THREAD

**Issue by Nelbert442** [deroproject/astrobwt#4]
Looks like the link previously pointing to: "http://www.sfu.ca/~zhenman/files/C16-FCCM2019-BWT.pdf" under https://github.com/deroproject/astrobwt#explaining-astrobwt is no longer a valid link.

A quick google search appears that the new link is now: https://www.sfu.ca/~zhenman/files/SC3-FCCM2019-BWT.pdf

**Comment by CaptainDero** [comment]
New link updated and local copy of research pdf added in repo for future. 
Thanks @Nelbert442
